FROM php:7.4-fpm-alpine

WORKDIR /code

EXPOSE 9000

COPY devops/docker/app/command-dev.sh /opt/command-dev.sh

RUN apk --no-cache add --virtual .build-deps $PHPIZE_DEPS \
    && apk --update add zlib-dev git libxml2-dev \
    && docker-php-ext-install zip bcmath mbstring pdo pdo_mysql opcache simplexml \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-source delete \
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

# All things composer
RUN php -r 'readfile("https://getcomposer.org/installer");' > composer-setup.php \
	&& php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
	&& rm -f composer-setup.php \
	&& chown www-data.www-data /var/www

CMD /opt/command-dev.sh
